-- THIS IS THE QB-CORE/SHARED/VEHICLES.LUA

local Vehicles = {
        {
        model = 'tfremus',
        name = 'Remus Tsuki Edition',
        brand = 'Annis',
        price = 235000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'eurosx32wb',
        name = 'Euros X32 Custom',
        brand = 'Annis',
        price = 68500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'euros',
        name = 'Euros',
        brand = 'Annis',
        price = 35000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'kawaii',
        name = 'kawaii',
        brand = 'Annis',
        price = 18000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'roxanne',
        name = 'Roxanne',
        brand = 'Annis',
        price = 30000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'zr380c',
        name = 'ZR380 R',
        brand = 'Annis',
        price = 120000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'zr380s',
        name = 'ZR380 RS',
        brand = 'Annis',
        price = 115000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'rh4',
        name = 'Elegy RH4',
        brand = 'Annis',
        price = 13500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'S230',
        name = 's-230',
        brand = 'Annis',
        price = 45000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'ZR250',
        name = 'ZR-250',
        brand = 'Annis',
        price = 23500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'ZR',
        name = 'ZR-350',
        brand = 'Annis',
        price = 65000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'rh82',
        name = 'Elegy RH8 FR-Works',
        brand = 'Annis',
        price = 185000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'ZR390',
        name = 'ZR390',
        brand = 'Annis',
        price = 145000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'ELEGY',
        name = 'Elegy Retro Ute',
        brand = 'Annis',
        price = 15000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'ELEGYRH7',
        name = 'Elegy RH-7',
        brand = 'Annis',
        price = 45000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'MAJIMALM',
        name = 'Majima LM',
        brand = 'Annis',
        price = 1850000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'REMUSVERT',
        name = 'Remus Cabrio',
        brand = 'Annis',
        price = 16500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'BOZOCARD',
        name = 'Cardboard Bozozoku',
        brand = 'Annis',
        price = 1000000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'REMUSP',
        name = 'Remus Pickup',
        brand = 'Annis',
        price = 24500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'TRAILW',
        name = 'Trailwilder',
        brand = 'Annis',
        price = 33500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'NCAVALCADE',
        name = 'Cavalcade III',
        brand = 'Albany',
        price = 70000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'PRIMOLX',
        name = 'Primo LX',
        brand = 'Albany',
        price = 33500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'ESPERANTO',
        name = 'Esperanto',
        brand = 'Albany',
        price = 14500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'ESPEXECUTIVE',
        name = 'Esperanto Executive',
        brand = 'Albany',
        price = 17500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'PRIMOARD',
        name = 'Primo ARD',
        brand = 'Albany',
        price = 19500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'SCHAFTER3RS',
        name = 'Benefactor Schafter V12',
        brand = 'Benefactor',
        price = 43500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'kriegerc',
        name = 'Benefactor kriegerc',
        brand = 'Benefactor',
        price = 335000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'glendalelimo',
        name = 'Benefactor Glendale Strech',
        brand = 'Benefactor',
        price = 675000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'streiter2',
        name = 'Benefactor streiter v2',
        brand = 'Benefactor',
        price = 93500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'spritzer',
        name = 'Benefactor spritzer',
        brand = 'Benefactor',
        price = 63500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'spritzerdtm',
        name = 'Benefactor spritzer STM',
        brand = 'Benefactor',
        price = 94500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'SCHLAGENSTR',
        name = 'Benefactor Schlagen STR',
        brand = 'Benefactor',
        price = 265000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'SCDTM',
        name = 'Benefactor Schwartzer DTM',
        brand = 'Benefactor',
        price = 665000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'SURANOE',
        name = 'Benefactor Surano E-Motion',
        brand = 'Benefactor',
        price = 845000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'yubbynub',
        name = 'Lazyeye Gauntlet',
        brand = 'Bravado',
        price = 33500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'HELLFIRELASTCALL',
        name = 'Bravado Gauntlet Hellfire Last Call',
        brand = 'Bravado',
        price = 66500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'buffalo4h',
        name = 'Bravado Hellfire',
        brand = 'Bravado',
        price = 85000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'gauntletc',
        name = 'Bravado Gauntlet v2',
        brand = 'Bravado',
        price = 47500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'gauntletstx',
        name = 'Bravado Gauntlet STX',
        brand = 'Bravado',
        price = 82500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'vulture',
        name = 'Bravado Vulture',
        brand = 'Bravado',
        price = 63500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'HOWITZER',
        name = 'Bravado Howitzer',
        brand = 'Bravado',
        price = 88500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'HOWITZER2',
        name = 'Bravado Howitzer v2',
        brand = 'Bravado',
        price = 93500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'GRESLEYH',
        name = 'Bravado Gresley Hellhound',
        brand = 'Bravado',
        price = 11350,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'servicevan',
        name = 'Boxville Bravado MBU',
        brand = 'Bravado',
        price = 45000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'sabuffalostreet',
        name = 'Buffalo Street',
        brand = 'Bravado',
        price = 80000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'sagauntletstreet',
        name = 'Buffalo Gauntlet Street',
        brand = 'Bravado',
        price = 135000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'CLUBTA',
        name = 'BF Club racing',
        brand = 'BF',
        price = 12300,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'weevilf6',
        name = 'BF Ruff-Weld Weevil',
        brand = 'BF',
        price = 2350000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'arias',
        name = 'BORDEAUX ARIAS',
        brand = 'BORDEAUX',
        price = 85000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'Mirage',
        name = 'Bordeaux SP3 Mirage',
        brand = 'BORDEAUX',
        price = 33500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'RAIDENZ',
        name = 'Coil Raiden Z',
        brand = 'COIL',
        price = 43000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'ROMTUNER',
        name = 'Chariot Romero Hearse Widebody',
        brand = 'Chariot',
        price = 43500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'picadorexr',
        name = 'Cheval picadorexr',
        brand = 'Cheval',
        price = 33500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'coquette4c',
        name = 'coquette 4c',
        brand = 'coquette',
        price = 76500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'h4rxgranUT',
        name = 'Declasse Granger 3600UT',
        brand = 'Declasse',
        price = 86500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'indiana',
        name = 'Declasse Indiana',
        brand = 'Declasse',
        price = 28500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'indianaxl',
        name = 'Declasse Indiana XL',
        brand = 'Declasse',
        price = 33500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = '91prem',
        name = '1991 Declasse Premier',
        brand = 'Declasse',
        price = 12850,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'l35r',
        name = 'Declasse Walton v1',
        brand = 'Declasse',
        price = 24500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'l35s',
        name = 'Declasse Walton v2',
        brand = 'Declasse',
        price = 19500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'burritor',
        name = 'Declasse Burritor',
        brand = 'Declasse',
        price = 33500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'gstyosemite1',
        name = 'Declasse Yosemite Raid',
        brand = 'Declasse',
        price = 64500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'TAMPAX',
        name = 'Declasse Tampa X wildbody',
        brand = 'Declasse',
        price = 135000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'TMPREM',
        name = 'Declasse Premier 200 SS',
        brand = 'Declasse',
        price = 22800,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'peanut',
        name = 'Dinka Peanut',
        brand = 'DINKA',
        price = 13500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'kanjor',
        name = 'Dinka Blista Kanjo Rally',
        brand = 'DINKA',
        price = 53500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'JESTGPR',
        name = 'Dinka Jester re-RR',
        brand = 'DINKA',
        price = 165000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'MILLENNIAL',
        name = 'Dinka Millennial Wagon',
        brand = 'DINKA',
        price = 41500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'NEXUS',
        name = 'Dinka Nexus',
        brand = 'DINKA',
        price = 235000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'chavosv6w',
        name = 'Cavos V6 WideBody',
        brand = 'Dinka',
        price = 350000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'jester3c',
        name = 'Jester MK4 Custom',
        brand = 'dINKA',
        price = 185000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'h4rxwindsorcus',
        name = 'Enus Windsor GP Kit',
        brand = 'Enus',
        price = 365000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'paragonxr',
        name = 'ENUS Paragon XR',
        brand = 'Enus',
        price = 245000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'sheavas',
        name = 'Emperor Sheavas',
        brand = 'Emperor',
        price = 31500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'stingersc',
        name = 'Grotti Stinger SC',
        brand = 'Grotti',
        price = 185000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'cheetahfel',
        name = 'grotti Cheetah Fel',
        brand = 'Grotti',
        price = 225000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'italigts',
        name = 'Grotti itali gts',
        brand = 'Grotti',
        price = 375000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'turismoc',
        name = 'Grotti Turismo Classic Custom',
        brand = 'Grotti',
        price = 1400000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'ITALIGTON',
        name = 'Grotti Itali GTO N-Larga Custom',
        brand = 'Grotti',
        price = 285000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'baller7r',
        name = 'gallivanter baller RAID',
        brand = 'gallivanter',
        price = 135000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'eva',
        name = 'hijak EVA',
        brand = 'hijak',
        price = 10000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'CARUMBA',
        name = 'Iemanjá Carumba',
        brand = 'Iemanjá',
        price = 10000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'dukes4',
        name = 'Imponte Duke 450 cui',
        brand = 'Imponte',
        price = 18500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'ruiner6str',
        name = 'Imponte Ruiner 450 Custom',
        brand = 'Imponte',
        price = 28500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'ruinerafd',
        name = 'Imponte Ruiner UTE',
        brand = 'Imponte',
        price = 32500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'FIRECAST',
        name = 'Imponte Firecast Phoenix',
        brand = 'Imponte',
        price = 63500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'DELUXOGT',
        name = 'Imponte Deluxo GT',
        brand = 'Imponte',
        price = 44500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'atlas',
        name = 'Karin atlas',
        brand = 'KARIN',
        price = 13500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'SULTANRSV8',
        name = 'Karin Sultan RSV8 MK2',
        brand = 'KARIN',
        price = 67500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'FUTOPE',
        name = 'Karin Futo Custom',
        brand = 'KARIN',
        price = 135000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'ARIANT',
        name = 'Karin Ariant',
        brand = 'KARIN',
        price = 83500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'BOORC',
        name = 'Karin Boor Widebody',
        brand = 'KARIN',
        price = 99500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'REBELD',
        name = 'Karin Drift Rebel',
        brand = 'KARIN',
        price = 279500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'N2FUTO',
        name = 'Karin Futo Hatchback N2 Spec',
        brand = 'KARIN',
        price = 65000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'R70K',
        name = 'Karin R70K-II',
        brand = 'KARIN',
        price = 1150000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'SULBOOST',
        name = 'Karin Sultan Backyard Boost',
        brand = 'KARIN',
        price = 85000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'SULTAN2C',
        name = 'Karin Sultan Classic Custom',
        brand = 'KARIN',
        price = 115000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'turtle',
        name = 'Karin Turtle',
        brand = 'KARIN',
        price = 22500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'KTUBE',
        name = 'Karin Sultan Tubular',
        brand = 'KARIN',
        price = 33500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'REBELR',
        name = 'Karin Rebel Raid',
        brand = 'KARIN',
        price = 95000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'SULTANDM',
        name = 'Karin Sultan Drift Missile',
        brand = 'KARIN',
        price = 16500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'panorama',
        name = 'Lampadati Panorama',
        brand = 'Lampadati',
        price = 22500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'KOMODAFR',
        name = 'Lampadati Komoda FR-Works',
        brand = 'Lampadati',
        price = 67500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'sunrise1',
        name = 'Maibatsu Sunrise VII',
        brand = 'Maibatsu',
        price = 49500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'PENTRO',
        name = 'Maibatsu Penumbra Retro',
        brand = 'Maibatsu',
        price = 22500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'VINCENT2',
        name = 'Maibatsu Vincent Sport',
        brand = 'Maibatsu',
        price = 63500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'VINCENT3',
        name = 'Maibatsu Vincent Tourer',
        brand = 'Maibatsu',
        price = 93500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'MOLECULE',
        name = 'Maxwell Molecule',
        brand = 'MAXWELL',
        price = 110000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'NINER',
        name = 'Obey 9R',
        brand = 'OBEY',
        price = 165000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'ARGENTO',
        name = 'Obey Argento',
        brand = 'OBEY',
        price = 83500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'DOUBLED',
        name = 'Obey DD-BLITZ',
        brand = 'OBEY',
        price = 9850,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'H4REntityMTR',
        name = 'Entity MTR',
        brand = 'Overflod',
        price = 1800000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'ORACLETA',
        name = 'Oracle V12',
        brand = 'ORACLE',
        price = 37500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'ORACLESTD',
        name = 'Oracle V12 std',
        brand = 'ORACLE',
        price = 97500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'f620s2',
        name = 'Ocelot 620s',
        brand = 'Ocelot',
        price = 35000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'squaddier',
        name = 'Patriot squaddier Raid',
        brand = 'Patriot',
        price = 135000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'cometrr',
        name = 'Pfister Comet RR',
        brand = 'Pfister',
        price = 235000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'comet6scw',
        name = 'Pfister Comet S2 SCW',
        brand = 'Pfister',
        price = 375000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'meteor',
        name = 'Pfister Meteor',
        brand = 'Pfister',
        price = 195000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'stardust',
        name = 'Pfister Stardust',
        brand = 'Pfister',
        price = 650000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'cometcup',
        name = 'Pfister Comet S2 CUP',
        brand = 'Pfister',
        price = 995000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'ares',
        name = 'Progen Ares GT',
        brand = 'Progen',
        price = 635000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'EMERUSGTR',
        name = 'Progen Emerus GTR',
        brand = 'Progen',
        price = 475000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'MF1',
        name = 'Progen MF1 Spyder',
        brand = 'Progen',
        price = 275000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'MF1C',
        name = 'Progen MF1 Spyder v2',
        brand = 'Progen',
        price = 275000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'OSIRISR',
        name = 'Pegassi Osiris Roadster',
        brand = 'Pegassi',
        price = 650000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'TEMPESTAES',
        name = 'Pegassi Tempesta Evo Stradale',
        brand = 'Pegassi',
        price = 375000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'tempesta2',
        name = 'Pegassi Tempesta Custom',
        brand = 'Pegassi',
        price = 475000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'TEMPESTAFR',
        name = 'Pegassi Tempesta FR-Works',
        brand = 'Pegassi',
        price = 850000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'TOREROD',
        name = 'Pegassi Torero Custom',
        brand = 'Pegassi',
        price = 650000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'saseverowb',
        name = 'Severo Widebody',
        brand = 'Pegassi',
        price = 1375000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'FUSILADEV8',
        name = 'Schyster Fusilade V8',
        brand = 'Schyster',
        price = 63500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'BERETTA',
        name = 'Übermacht Beretta',
        brand = 'Ubermacht',
        price = 27500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'sentinelsg4',
        name = 'Übermacht sentinelsg4',
        brand = 'Ubermacht',
        price = 33500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'zion4',
        name = 'Übermacht Zion 750ci',
        brand = 'Ubermacht',
        price = 27500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'CYPHERCT',
        name = 'Ubermacht Cypher Hatchback',
        brand = 'Ubermacht',
        price = 44500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'sentinel6str2',
        name = 'Ubermacht Sentinel Classic Custom',
        brand = 'Ubermacht',
        price = 39500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'SENTINELDM',
        name = 'Ubermacht Sentinel SG4 Drift Missile',
        brand = 'Ubermacht',
        price = 34500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'ZIONV10',
        name = 'Übermacht Zion V10',
        brand = 'Ubermacht',
        price = 56500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'cypherx9',
        name = 'Cypher MX-2',
        brand = 'Ubermacht',
        price = 45000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'fmjb',
        name = 'Custom FMJ Bullet',
        brand = 'VAPID',
        price = 265000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'CONTENDERBAJA',
        name = 'Vapid Contender Baja',
        brand = 'VAPID',
        price = 47500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'CARACARAN',
        name = '2022 Vapid Caracara',
        brand = 'VAPID',
        price = 33500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'torrence',
        name = 'Vapid Torrence',
        brand = 'VAPID',
        price = 48500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'DOMGTCOUPE',
        name = 'Vapid Dominator GT Coupe',
        brand = 'VAPID',
        price = 97500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'vamoswb',
        name = 'Vamos Custom',
        brand = 'Vapid',
        price = 220000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'NSANDSTORM',
        name = 'Vapid Sandstorm D350',
        brand = 'VAPID',
        price = 88500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'nsandstorm',
        name = 'Sandstorm D350',
        brand = 'VAPID',
        price = 88500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'nsandstorm2',
        name = 'Sandstorm D350 XL',
        brand = 'VAPID',
        price = 88500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'hellenstorm',
        name = 'Sandstorm D350 Hellenbach',
        brand = 'VAPID',
        price = 88500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'sandstorm',
        name = 'Vapid Sandstorm v1',
        brand = 'VAPID',
        price = 88500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'sandstormxl',
        name = 'Vapid Sandstorm v2',
        brand = 'VAPID',
        price = 88500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'sandstormev',
        name = 'Vapid Sandstorm v3',
        brand = 'VAPID',
        price = 88500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'benson2',
        name = 'Vapid Benson V2',
        brand = 'VAPID',
        price = 88500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'nspeedo',
        name = 'Vapid Speedoo v2',
        brand = 'VAPID',
        price = 88500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'executioner',
        name = 'Vapid executioner',
        brand = 'VAPID',
        price = 88500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'dominatorgtc',
        name = 'Vapid Dominator 450ci',
        brand = 'VAPID',
        price = 37500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'clique2',
        name = 'Vapid Clique v2',
        brand = 'VAPID',
        price = 49500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'domc',
        name = 'Vapid Dominator 550ci',
        brand = 'VAPID',
        price = 33500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'CONTENDERC',
        name = 'Vapid Contender Custom',
        brand = 'VAPID',
        price = 18500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'domgt',
        name = 'Vapid Nightmare GT',
        brand = 'VAPID',
        price = 335000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'bcatctx',
        name = 'Vapid Bobcat CTX (Bagcat)',
        brand = 'VAPID',
        price = 22850,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'gstriata1',
        name = 'Vapid Riata CTX',
        brand = 'VAPID',
        price = 33500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'RIATAO',
        name = 'Vapid Riata Outlaw',
        brand = 'VAPID',
        price = 19500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'HACHURAC',
        name = 'Vulcar Hachura R Custom',
        brand = 'VULCAR',
        price = 375000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'NEBULAW',
        name = 'Vulcar Nebula Wagon',
        brand = 'VULCAR',
        price = 285000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'vigerozxwbc',
        name = 'Vigero ZX WideBody',
        brand = 'Vigero',
        price = 93500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'vigerozxwb',
        name = 'VigeroZX WideBody Convertible',
        brand = 'Vigero',
        price = 93500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'elegant',
        name = 'Willard Elegant',
        brand = 'Willard',
        price = 65000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'paradox',
        name = 'Willard Paradox',
        brand = 'Willard',
        price = 37500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'paradox2',
        name = 'Willard Paradox (HotRing)',
        brand = 'Willard',
        price = 28500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'warrener3',
        name = 'Warrener HKR WideBody',
        brand = 'Warrener',
        price = 16500,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'hotknifec',
        name = 'Hotknife Custom',
        brand = 'Vapid',
        price = 5000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'domttc',
        name = 'Dominator GTT',
        brand = 'Vapid',
        price = 5000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'T20',
        name = 'REPLACE',
        brand = 'REPLACE',
        price = 5000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'T20',
        name = 'Progen T20',
        brand = 'Progen',
        price = 5000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'TIGON',
        name = 'Lampadati  TIGON',
        brand = 'Lampadati ',
        price = 5000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'VACCA',
        name = 'VACCA',
        brand = 'pagassi',
        price = 5000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'ZENTORNO',
        name = 'ZENTORNO',
        brand = 'pagassi',
        price = 5000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'VAGNER',
        name = 'VAGNER',
        brand = ' Dewbauchee',
        price = 5000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'ENTITYXF',
        name = 'ENTITYXF',
        brand = 'Overflood',
        price = 5000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'ENTITY2',
        name = 'ENTITY2',
        brand = 'Overflood',
        price = 5000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'ENTITY3',
        name = 'ENTITY3',
        brand = 'Overflood',
        price = 5000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'FMJ',
        name = 'FMJ',
        brand = 'Vapid',
        price = 5000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'ADDER',
        name = 'ADDER',
        brand = 'Truffade',
        price = 5000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'THRAX',
        name = 'THRAX',
        brand = 'Truffade',
        price = 5000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'COMET2',
        name = 'COMET2',
        brand = 'Pfister',
        price = 5000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'CHEETAH2',
        name = 'CHEETAH2',
        brand = 'Grotti',
        price = 5000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'BUFFALO4',
        name = 'BUFFALO4',
        brand = ' Bravado',
        price = 5000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'BUFFALO5',
        name = 'BUFFALO5',
        brand = 'Bravado',
        price = 5000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
    {
        model = 'CHEETAH2',
        name = 'CHEETAH2',
        brand = 'Grotti',
        price = 5000,
        category = 'compacts',
        type = 'automobile',
        shop = 'pdm',
    },
}
